name:                demo
version:             0.1.0.0
github:              "arademaker/demo"
license:             BSD3
author:              "Alexandre Rademaker"
maintainer:          "arademaker@gmail.com"
copyright:           "2021 Alexandre Rademaker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arademaker/demo#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck 
- filepath
- safe
- random
- array

library:
  source-dirs:
    - src
    - src-tmp


executables:
  counter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - demo

tests:
  demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - demo
